# Generated by Django 3.2.4 on 2023-10-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Father_Name', models.CharField(max_length=200)),
                ('Mother_Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=150)),
                ('Class_For_Admission', models.IntegerField()),
            ],
        ),
    ]
